Refactor out states into separate classes
Elveskevtar/SmarterMoving pull request #5
Opened 2020-06-30 04:58 UTC by planetguy32

Also moves code generally into classes per movement state. (There are still scattered places outside State* that behave differently per state, but much of the state-specific code is collected. Client-side code is generally ignored in this refactor.)

Having code for each movement state placed based on the movement state makes more sense to me - if you disagree, feel free to close the PR.

2020-06-30 05:01 UTC, Elveskevtar commented
I really like this organization actually, makes a lot more sense. I'll do some testing tonight and tomorrow and would like to move to this. Great work!

2020-06-30 06:02 UTC, elveskevtar requested changes
Tested out and it works great. This is a much better design pattern. I requested a few nitpicks but once those are fixed, it's good to merge!!

If you could rebase your commits into 1 commit when doing the revision that would be amazing. Still need to make that contributing page.

2020-06-30 06:02 UTC, elveskevtar commented on src/main/java/net/smart/moving/player/state/StateHandlerCrawl.java
> +    public void afterOnUpdate(EntityPlayer player) {
Nitpick: add override annotation

2020-06-30 06:02 UTC, elveskevtar commented on src/main/java/net/smart/moving/player/state/StateHandlerCrawl.java
> +    public void updatePlayerRotations(EntityPlayer player, SmartBase smartBase) {
Nitpick: add override annotation

2020-06-30 06:02 UTC, Elveskevtar commented on src/main/java/net/smart/moving/player/state/StateHandlerIdle.java
> +    public void afterOnUpdate(EntityPlayer player) {
Nitpick: add override annotation

2020-07-01 01:32 UTC, elveskevtar approved these changes
Looks good to squash and merge!

2020-07-01 01:32 UTC, planetguy32 commented
I think I've set it up with the annotations you requested. I'm still not really Git literate, sorry about the bizarre state of things.

2020-07-01 01:38 UTC, Elveskevtar commented
That's okay! It's a little wonky but almost everything in git is fixable. Rebasing and squashing can be a little dangerous bc you're actually changing the repositories commit history so I would rather lean on the safer side than anything else.

2020-07-01 01:38 UTC, merged